In [5]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("C:\\Users\\SAYANJIT\\OneDrive\\Desktop\\project\\FIFA Player Analytics & Market Value Prediction\\data\\raw\\FC26_20250921.csv")
df

C:\Users\SAYANJIT\AppData\Local\Temp\ipykernel_28372\1745145524.py:1: DtypeWarning: Columns (0: player_tags) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:\\Users\\SAYANJIT\\OneDrive\\Desktop\\project\\FIFA Player Analytics & Market Value Prediction\\data\\raw\\FC26_20250921.csv")

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,252371,/player/252371/jude-bellingham/260004/,26,4,2025-09-19,J. Bellingham,Jude Victor William Bellingham,"CAM, CM",90,94,...,85+3,85+3,83+3,82+3,81+3,81+3,81+3,82+3,18+3,https://cdn.sofifa.net/players/252/371/26_120.png
1,239053,/player/239053/federico-valverde/260004/,26,4,2025-09-19,F. Valverde,Federico Santiago Valverde Dipetta,"CM, CDM, RB",89,90,...,87+3,87+3,86+3,86+3,83+3,83+3,83+3,86+3,18+3,https://cdn.sofifa.net/players/239/053/26_120.png
2,212622,/player/212622/joshua-kimmich/260004/,26,4,2025-09-19,J. Kimmich,Joshua Walter Kimmich,"CDM, RB, CM",89,89,...,87+2,87+2,86+3,85+3,82+3,82+3,82+3,85+3,21+3,https://cdn.sofifa.net/players/212/622/26_120.png
3,235212,/player/235212/achraf-hakimi/260004/,26,4,2025-09-19,A. Hakimi,Achraf Hakimi Mouhأشرف حكيمي,"RB, RM",89,90,...,83+3,83+3,86+3,86+3,81+3,81+3,81+3,86+3,17+3,https://cdn.sofifa.net/players/235/212/26_120.png
4,224232,/player/224232/nicolo-barella/260004/,26,4,2025-09-19,N. Barella,Nicolò Barella,CM,87,87,...,85+2,85+2,84+3,83+3,80+3,80+3,80+3,83+3,19+3,https://cdn.sofifa.net/players/224/232/26_120.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18400,267946,/player/267946/jun-sub-lim/260004/,26,4,2025-09-19,Lim Jun Sub,Joon-seob Im임준섭,GK,48,54,...,19+2,19+2,16+2,16+2,19+2,19+2,19+2,16+2,47+2,https://cdn.sofifa.net/players/267/946/26_120.png
18401,76593,/player/76593/jianxian-yu/260004/,26,4,2025-09-19,Yu Jianxian,Jianxian Yu,GK,49,56,...,18+2,18+2,16+2,16+2,19+2,19+2,19+2,16+2,48+2,https://cdn.sofifa.net/players/076/593/26_120.png
18402,77205,/player/77205/man-ho-park/260004/,26,4,2025-09-19,Park Man Ho,Man Ho Park,GK,48,59,...,19+2,19+2,17+2,16+2,17+2,17+2,17+2,16+2,47+2,https://cdn.sofifa.net/players/077/205/26_120.png
18403,278149,/player/278149/dipesh-chauhan/260004/,26,4,2025-09-19,D. Chauhan,Dipesh Chauhan,GK,51,61,...,17+2,17+2,17+2,17+2,16+2,16+2,16+2,17+2,50+2,https://cdn.sofifa.net/players/278/149/26_120.png
18404,79985,/player/79985/haochen-peng/260004/,26,4,2025-09-19,Peng Haochen,Haochen Peng,GK,49,58,...,18+2,18+2,15+2,15+2,16+2,16+2,16+2,15+2,48+2,https://cdn.sofifa.net/players/079/985/26_120.png

In [11]:
df.shape

(18405, 110)

In [12]:
df.columns

Index(['player_id', 'player_url', 'fifa_version', 'fifa_update',
       'fifa_update_date', 'short_name', 'long_name', 'player_positions',
       'overall', 'potential',
       ...
       'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk',
       'player_face_url'],
      dtype='str', length=110)

In [16]:
df[['overall','potential']].describe()

            overall     potential
count  18405.000000  18405.000000
mean      65.766965     71.165173
std        6.980628      6.403862
min       47.000000     49.000000
25%       61.000000     67.000000
50%       66.000000     71.000000
75%       70.000000     75.000000
max       91.000000     95.000000

In [17]:
df.dtypes

player_id           int64
player_url            str
fifa_version        int64
fifa_update         int64
fifa_update_date      str
                    ...
cb                    str
rcb                   str
rb                    str
gk                    str
player_face_url       str
Length: 110, dtype: object

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [player_id, player_url, fifa_version, fifa_update, fifa_update_date, short_name, long_name, player_positions, overall, potential, value_eur, wage_eur, age, dob, height_cm, weight_kg, league_id, league_name, league_level, club_team_id, club_name, club_position, club_jersey_number, club_loaned_from, club_joined_date, club_contract_valid_until_year, nationality_id, nationality_name, nation_team_id, nation_position, nation_jersey_number, preferred_foot, weak_foot, skill_moves, international_reputation, work_rate, body_type, real_face, release_clause_eur, player_tags, player_traits, pace, shooting, passing, dribbling, defending, physic, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking_awareness, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, goalkeeping_speed, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, ...]
Index: []

[0 rows x 110 columns]

In [24]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

fifa_version
26    18405
Name: count, dtype: int64
--------------------------------------------------
fifa_update
4    18405
Name: count, dtype: int64
--------------------------------------------------
fifa_update_date
2025-09-19    18405
Name: count, dtype: int64
--------------------------------------------------
league_level
1.0    13565
2.0     2884
3.0     1219
4.0      648
Name: count, dtype: int64
--------------------------------------------------
club_contract_valid_until_year
2026.0    6267
2027.0    4117
2028.0    3680
2025.0    1926
2029.0    1565
2030.0     716
2031.0      32
2032.0       8
2033.0       3
2034.0       1
2035.0       1
Name: count, dtype: int64
--------------------------------------------------
preferred_foot
Right    13908
Left      4497
Name: count, dtype: int64
--------------------------------------------------
weak_foot
3    11430
2     3987
4     2568
5      260
1      160
Name: count, dtype: int64
--------------------------------------------------
skill_moves
2    8858
3    6355
1    2062
4    1080
5      50
Name: count, dtype: int64
--------------------------------------------------
international_reputation
1    17591
3      472
2      275
4       52
5       15
Name: count, dtype: int64
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
body_type
Normal (170-185)    6055
Normal (185+)       4298
Lean (170-185)      3830
Lean (185+)         2289
Normal (170-)        526
Stocky (170-185)     456
Stocky (185+)        379
Lean (170-)          369
Unique               133
Stocky (170-)         70
Name: count, dtype: int64
--------------------------------------------------
real_face
No     15637
Yes     2768
Name: count, dtype: int64
--------------------------------------------------

In [30]:
df.info(verbose=True,show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 18405 entries, 0 to 18404
Data columns (total 110 columns):
 #    Column                          Non-Null Count  Dtype
---   ------                          --------------  -----
 0    player_id                       18405 non-null  int64
 1    player_url                      18405 non-null  str
 2    fifa_version                    18405 non-null  int64
 3    fifa_update                     18405 non-null  int64
 4    fifa_update_date                18405 non-null  str
 5    short_name                      18405 non-null  str
 6    long_name                       18405 non-null  str
 7    player_positions                18405 non-null  str
 8    overall                         18405 non-null  int64
 9    potential                       18405 non-null  int64
 10   value_eur                       18405 non-null  int64
 11   wage_eur                        18405 non-null  int64
 12   age                             18405 non-null  int64
 13   dob                             18405 non-null  str
 14   height_cm                       18405 non-null  int64
 15   weight_kg                       18405 non-null  int64
 16   league_id                       18316 non-null  float64
 17   league_name                     18316 non-null  str
 18   league_level                    18316 non-null  float64
 19   club_team_id                    18316 non-null  float64
 20   club_name                       18316 non-null  str
 21   club_position                   18316 non-null  str
 22   club_jersey_number              18316 non-null  float64
 23   club_loaned_from                1325 non-null   str
 24   club_joined_date                16991 non-null  str
 25   club_contract_valid_until_year  18316 non-null  float64
 26   nationality_id                  18405 non-null  int64
 27   nationality_name                18405 non-null  str
 28   nation_team_id                  728 non-null    float64
 29   nation_position                 728 non-null    str
 30   nation_jersey_number            728 non-null    float64
 31   preferred_foot                  18405 non-null  str
 32   weak_foot                       18405 non-null  int64
 33   skill_moves                     18405 non-null  int64
 34   international_reputation        18405 non-null  int64
 35   work_rate                       0 non-null      float64
 36   body_type                       18405 non-null  str
 37   real_face                       18405 non-null  str
 38   release_clause_eur              16971 non-null  float64
 39   player_tags                     950 non-null    str
 40   player_traits                   7616 non-null   str
 41   pace                            16343 non-null  float64
 42   shooting                        16343 non-null  float64
 43   passing                         16343 non-null  float64
 44   dribbling                       16343 non-null  float64
 45   defending                       16343 non-null  float64
 46   physic                          16343 non-null  float64
 47   attacking_crossing              18405 non-null  int64
 48   attacking_finishing             18405 non-null  int64
 49   attacking_heading_accuracy      18405 non-null  int64
 50   attacking_short_passing         18405 non-null  int64
 51   attacking_volleys               18405 non-null  int64
 52   skill_dribbling                 18405 non-null  int64
 53   skill_curve                     18405 non-null  int64
 54   skill_fk_accuracy               18405 non-null  int64
 55   skill_long_passing              18405 non-null  int64
 56   skill_ball_control              18405 non-null  int64
 57   movement_acceleration           18405 non-null  int64
 58   movement_sprint_speed           18405 non-null  int64
 59   movement_agility                18405 non-null  int64
 60   movement_reactions              18405 non-null  int64
 61   movement_balance                18405 non-null  int64
 62   power_shot_power                18405 non-null  int64
 63   power_jumping                   18405 non-null  int64
 64   power_stamina                   18405 non-null  int64
 65   power_strength                  18405 non-null  int64
 66   power_long_shots                18405 non-null  int64
 67   mentality_aggression            18405 non-null  int64
 68   mentality_interceptions         18405 non-null  int64
 69   mentality_positioning           18405 non-null  int64
 70   mentality_vision                18405 non-null  int64
 71   mentality_penalties             18405 non-null  int64
 72   mentality_composure             18405 non-null  int64
 73   defending_marking_awareness     18405 non-null  int64
 74   defending_standing_tackle       18405 non-null  int64
 75   defending_sliding_tackle        18405 non-null  int64
 76   goalkeeping_diving              18405 non-null  int64
 77   goalkeeping_handling            18405 non-null  int64
 78   goalkeeping_kicking             18405 non-null  int64
 79   goalkeeping_positioning         18405 non-null  int64
 80   goalkeeping_reflexes            18405 non-null  int64
 81   goalkeeping_speed               2062 non-null   float64
 82   ls                              18405 non-null  str
 83   st                              18405 non-null  str
 84   rs                              18405 non-null  str
 85   lw                              18405 non-null  str
 86   lf                              18405 non-null  str
 87   cf                              18405 non-null  str
 88   rf                              18405 non-null  str
 89   rw                              18405 non-null  str
 90   lam                             18405 non-null  str
 91   cam                             18405 non-null  str
 92   ram                             18405 non-null  str
 93   lm                              18405 non-null  str
 94   lcm                             18405 non-null  str
 95   cm                              18405 non-null  str
 96   rcm                             18405 non-null  str
 97   rm                              18405 non-null  str
 98   lwb                             18405 non-null  str
 99   ldm                             18405 non-null  str
 100  cdm                             18405 non-null  str
 101  rdm                             18405 non-null  str
 102  rwb                             18405 non-null  str
 103  lb                              18405 non-null  str
 104  lcb                             18405 non-null  str
 105  cb                              18405 non-null  str
 106  rcb                             18405 non-null  str
 107  rb                              18405 non-null  str
 108  gk                              18405 non-null  str
 109  player_face_url                 18405 non-null  str
dtypes: float64(16), int64(48), str(46)
memory usage: 15.4 MB